### ISSUE TITLE
No dev tools

### ISSUE THREAD

**Issue by JuhQ** [VPenkov/okayNav#10]
There doesn't seem to be any dev tools, like gulp or grunt, in the repo, not any mention which tool to use to convert less to css and to minify js&css

**Comment by Johann-S** [comment]
Is it possible to see the progress of this issue @VPenkov ? Maybe I can help a bit

**Comment by VPenkov** [comment]
Gulp has been added.
Unfortunately I'm pretty new to all that Gulp stuff.

Anyone care to provide some feedback?

**Comment by Johann-S** [comment]
It's a good beginning :+1: 

In my opinion it would be usefull to have tools to check the quality of the code like JSHint, JSCS 

See : 
- https://github.com/jscs-dev/gulp-jscs
- https://github.com/spalger/gulp-jshint

**Comment by VPenkov** [comment]
I need to prioritize other things here, pull requests are welcome.
