### ISSUE TITLE
Requires flexbox

### ISSUE THREAD

**Issue by tunapuff** [VPenkov/okayNav#11]
I noticed that the plugin is dependant on the flexbox properties you have for the <header> in style.css of your demo. Without it, the menu links don't return to their visible state when resizing the browser.

Is it possible to remove the flexbox dependencies?

Example: http://codepen.io/anon/pen/obrKEE

**Comment by VPenkov** [comment]
Browsers which don't support flexbox are now unsupported by their authors (e.g. Microsoft).
According to caniuse.com, 95.89% of the browsers support flexbox, including mobile devices. That's what we're dealing with here.

With that in mind, you can still use floats. Probably.

An improved version of okayNav is coming in the next few days which may take care of this.

Flexbox makes a ton of things easier and everyone should start using it. Even YouTube are using it on gaming.youtube.com.

**Comment by VPenkov** [comment]
Fixed in the current version. Nav will now work with floats as well.

**Comment by clemsontiger** [comment]
is there an example using it with floats instead of flexbox?
