### ISSUE TITLE
Should the ellipsis dots be horizontal initially and open to vertical?

### ISSUE THREAD

**Issue by josephfusco** [VPenkov/okayNav#15]
Of course this might be opinionated, but can there be built in options for it if no? :smile:

**Comment by VPenkov** [comment]
Hm, I guess they could be. But the standard behaviour is to be vertical. It's like the three lines menu icon (which is called a hamburger menu), but this one has another catchy name - kebab menu icon.

I guess you could always edit the CSS file and swap the transition property for the icon states. No reason to do this via javascript.

**Comment by josephfusco** [comment]
True with editing the CSS, I was also looking at how Edge browser does it in the demo gif. :smile:

**Comment by VPenkov** [comment]
I'm closing this now because it's directly editable by swapping two CSS properties. Feel free to further address the issue if you feel it's necessary.
