### ISSUE TITLE
Item Priority

### ISSUE THREAD

**Issue by brentjett** [VPenkov/okayNav#16]
Love the library! Would love to see it support a priority value on each nav item so that lower priority items are hidden/moved before higher ones. Many times the last item in a menu is the primary call-to-action or contact link and shouldn't be hidden until there's really no other option. 

Thanks again for writing the library!

**Comment by VPenkov** [comment]
This is a duplicate of https://github.com/VPenkov/okayNav/issues/6.
Currently I'm looking for a way to implement this.
