### ISSUE TITLE
CSS: split styling / positioning

### ISSUE THREAD

**Issue by Pascalmh** [VPenkov/okayNav#19]
Styling stuff like colors, margins, paddings should not go into the same .css-file as postioning, dislay-properties, etc.

Currently you have to override a lot of stuff okaynav does. Not everyone has a white background header, this should go into somekind of theme.css-File.

Workflow could then be:
Demo it using
- `dist/okaynav.css`
- `dist/okaynav-defaulttheme.css`

Use it in production using only `style/okaynav.css` + `myprojectsstyle.css`.

**Comment by VPenkov** [comment]
Oh yeah, I was wondering what feels wrong with my CSS.
Thanks, I'll definitely do that asap.
