### ISSUE TITLE
Option to defined which items should always show

### ISSUE THREAD

**Issue by Yearhouse** [VPenkov/okayNav#24]
Is there a way to define items which should always be visible/not hidden?

If I have a login link which like so:

link1 link2 link3 link4 link5 login

I would like the other links to be hidden but the login link to be visible

**Comment by Yearhouse** [comment]
If I had read the roadmap I would have answered my own question :)

**Comment by VPenkov** [comment]
Yeah, and the other open issues too (https://github.com/VPenkov/okayNav/issues/6) :)

Do stop by occasionally, I already have a concept for this, and I'm working on it.
