### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [VPenkov/okayNav#25]
Hi there!
This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because you can get some support to okayNav.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like okayNav.
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work!

**Comment by VPenkov** [comment]
Yeah, I've left a link to my PayPal [at the bottom of the readme](https://github.com/VPenkov/okayNav#buy-me-a-beer). Probably should remove it as I haven't gotten any donations yet so it just clutters the document.

**Comment by Francolpm** [comment]
Yeah! I saw the button but maybe you get some extra money in beerpay.io

Don't forget delete this false issue!
Thanks for reply!
Cheers!
