### ISSUE TITLE
AMD/CommonJS support

### ISSUE THREAD

**Issue by VPenkov** [VPenkov/okayNav#3]

**Comment by VPenkov** [comment]
Pull requests are accepted on this one.

**Comment by mrmartineau** [comment]
I suggest CommonJS support rather than AMD.. although creating support for both is trivial :wink: 

See https://github.com/umdjs/umd or http://bob.yexley.net/umd-javascript-that-runs-anywhere/ for more info

**Comment by VPenkov** [comment]
Thanks, I'll make sure this gets handled soon.
