### ISSUE TITLE
not work on iOS < 9.0

### ISSUE THREAD

**Issue by dimensi** [VPenkov/okayNav#52]
Plugin does not turn off the menu.
![53d90d2f5623a0da09ad98595ad7737c9402b92a0cc78374f6 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11390039/18128849/77aefcea-6f90-11e6-869c-f6adb65cdea4.jpg)
Iphone 6, ios 8.4. I don't know how to fix it... On ios > 9.0 work good.
Thx advance.

**Comment by BlackSkorpio** [comment]
@VPenkov will this issue be covered in the coming update?
Or better yet, maybe a fix for the current version?

Asking since I'm looking to Incorporate the okayNav in a project that I'm working on, and cant figure out what is causing the menu not to display on iOS 9 ->
