### ISSUE TITLE
Menu icon getting misaligned on iOS Safari

### ISSUE THREAD

**Issue by typhoon2099** [VPenkov/okayNav#57]
I've run into an issue where the menu icon gets pushed down onto a new line on Safari on iOS (tested on an iPhone 5S running iOS 10.2). The issue popped up during bugtesting on a project but can be seen on the Codepen found in the readme.

[Here's a screenshot](http://imgur.com/a/XBQAj)

Adjusting any of the CSS in the developer tools instantly fixes this, so appears to occur on the initial render.

Cheers,
Matthew Simpson

**Comment by michaelwilhelmsen** [comment]
+1 I have the exact same issue

**Comment by lgfstudio** [comment]
You can changehange the CSS to have the toggle fixed, as you need in the corner of the page all the time anyway...

.okayNav__menu-toggle {
	position: fixed !important;
	z-index: 999;
	top: 15px;
	right: -5px;
	float: left;
	width: 60px;
	height: 20px;
	cursor: pointer;
	transition: -webkit-transform .4s cubic-bezier(.55, 0, .1, 1);
	transition: transform .4s cubic-bezier(.55, 0, .1, 1);
	transition: transform .4s cubic-bezier(.55, 0, .1, 1), -webkit-transform .4s cubic-bezier(.55, 0, .1, 1)
}
