### ISSUE TITLE
Expandable UL does not close when touching out of it on iPad Safari

### ISSUE THREAD

**Issue by GreggOD** [VPenkov/okayNav#9]
Hi,

Device: iPad
Model: Unsure
Browser: Safari

Issue:  ".okayNav__nav--invisible .nav-open" does not collapse when touching elsewhere on the screen. You have to click on the menu-toggle.

Compliments: Great plugin and thanks for reshaping the way menu's break down :)

**Comment by VPenkov** [comment]
Is this a Safari-only issue?
Can I get a link to your website?

If it's not okay to share it in public, please drop me an email on hi@vergilpenkov.com

**Comment by drakmail** [comment]
Doesn't know, does it related, but noticed, that if click in desktop safari in empty area under menu – it doesn't close too (when click at left part of menu – it closes). See image:
![2016-02-24 10-56-17 codepen - okaynav demo](https://cloud.githubusercontent.com/assets/869453/13278990/8c361c10-dae5-11e5-91d2-99dbbe26bb53.png)

**Comment by VPenkov** [comment]
This is somewhat intentional.
The latest update adds the proper styling to indicate where you can tap to close the navigation.
